const [productList, setProductList] = useState([
    {
      id: 1,
      name: "Mango",
      price: 30,
      quantityAvailable: 12,
      category: "Fruits",
      image: Mango,
      quantity: 0,
    },
    {
      id: 2,
      name: "Apple",
      price: 50,
      quantityAvailable: 20,
      category: "Fruits",
      image: Apple,
      quantity: 0,
    },
    {
      id: 3,
      name: "Banana",
      price: 10,
      quantityAvailable: 100,
      category: "Fruits",
      image: Banana,
      quantity: 0,
    },
    {
      id: 4,
      name: "Orange",
      price: 25,
      quantityAvailable: 25,
      category: "Fruits",
      image: oranges,
      quantity: 0,
    },
    {
      id: 5,
      name: "Pond's Powder",
      price: 130,
      quantityAvailable: 12,
      category: "Cosmetics",
      image: ponds,
      quantity: 0,
    },
    {
      id: 6,
      name: "VLCC Sun Screen",
      price: 200,
      quantityAvailable: 12,
      category: "Cosmetics",
      image: sunscreen,
      quantity: 0,
    },
    {
      id: 7,
      name: "Coconut oil",
      price: 80,
      quantityAvailable: 12,
      category: "Cosmetics",
      image: coconutOil,
      quantity: 0,
    },
    {
      id: 8,
      name: "Rose Water",
      price: 40,
      quantityAvailable: 12,
      category: "Cosmetics",
      image: rosewater,
      quantity: 0,
    },
    {
      id: 9,
      name: "Tomatoes",
      price: 30,
      quantityAvailable: 12,
      category: "Vegetables",
      image: Tomato,
      quantity: 0,
    },
    {
      id: 10,
      name: "Brinjal",
      price: 30,
      quantityAvailable: 12,
      category: "Vegetables",
      image: brinjal,
      quantity: 0,
    },
    {
      id: 11,
      name: "Drum Stick",
      price: 10,
      quantityAvailable: 12,
      category: "Vegetables",
      image: drumstick,
      quantity: 0,
    },
    {
      id: 12,
      name: "Potatoes",
      price: 30,
      quantityAvailable: 12,
      category: "Vegetables",
      image: potatoes,
      quantity: 0,
    },
    {
      id: 13,
      name: "T-shirt",
      price: 500,
      quantityAvailable: 12,
      category: "Clothing",
      image: Teeshirt,
      quantity: 0,
    },
    {
      id: 14,
      name: "Formal Shirt",
      price: 30,
      quantityAvailable: 12,
      category: "Clothing",
      image: FormalShirt,
      quantity: 0,
    },
    {
      id: 15,
      name: "Tie",
      price: 100,
      quantityAvailable: 12,
      category: "Clothing",
      image: tie,
      quantity: 0,
    },
    {
      id: 16,
      name: "Thumbs Up",
      price: 80,
      quantityAvailable: 12,
      category: "Beverages",
      image: Thumpsup,
      quantity: 0,
    },
    {
      id: 17,
      name: "Mazza",
      price: 110,
      quantityAvailable: 12,
      category: "Beverages",
      image: mazza,
      quantity: 0,
    },
  ]);